/**
 * Author: Claude Code using Sonnet 4
 * Date: 2025-09-28
 * PURPOSE: Enhanced model catalog with real OpenRouter data from arc-explainer project.
 *          Replaces hallucinated models with accurate OpenRouter API model definitions.
 *          Incorporates critical metadata fields for proper model handling and UI display.
 * SRP/DRY check: Pass - Single responsibility for model metadata, eliminates duplicate/fake model definitions
 * shadcn/ui: Pass - Configuration only, no UI components
 */

export type ModelDisplay = {
  key: string;                    // Model identifier (matches real OpenRouter API)
  name: string;                   // Display name for UI
  color: string;                  // Tailwind color class for UI theming
  premium: boolean;               // Whether to show premium badge
  cost: {                         // Formatted per-million token costs for display
    input: string;
    output: string;
  };
  provider: 'OpenAI' | 'Anthropic' | 'Gemini' | 'DeepSeek' | 'OpenRouter';
  responseTime: {
    speed: 'fast' | 'moderate' | 'slow';
    estimate: string;
  };

  // Enhanced fields from ModelConfig for accuracy
  apiModelName: string;           // Actual API model name
  modelType: string;              // Model type classification
  contextWindow?: number;         // Context window size
  maxOutputTokens?: number;       // Maximum output tokens
  releaseDate?: string;           // Release date (YYYY-MM format)

  // Capability flags (standardized naming)
  supportsTemperature?: boolean;  // Temperature parameter support
  isReasoning?: boolean;          // Reasoning/thinking model
  supportsStructuredOutput?: boolean;  // JSON mode support
  requiresPromptFormat?: boolean; // Special prompt formatting required
};

// Real model catalog based on arc-explainer project data (Source of Truth)
export const MODEL_CATALOG: Record<string, ModelDisplay> = {
  // OpenAI Models - Direct API
  'gpt-4.1-nano-2025-04-14': {
    key: 'gpt-4.1-nano-2025-04-14',
    name: 'GPT-4.1 Nano',
    color: 'bg-blue-500',
    premium: false,
    cost: { input: '$0.10', output: '$0.40' },
    provider: 'OpenAI',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'gpt-4.1-nano-2025-04-14',
    modelType: 'gpt5_chat',
    contextWindow: 1000000,
    releaseDate: '2025-04',
    supportsTemperature: true,
  },
  'gpt-4.1-mini-2025-04-14': {
    key: 'gpt-4.1-mini-2025-04-14',
    name: 'GPT-4.1 Mini',
    color: 'bg-purple-500',
    premium: false,
    cost: { input: '$0.40', output: '$1.60' },
    provider: 'OpenAI',
    responseTime: { speed: 'moderate', estimate: '30-60 sec' },
    apiModelName: 'gpt-4.1-mini-2025-04-14',
    modelType: 'gpt5_chat',
    contextWindow: 1000000,
    releaseDate: '2025-04',
    supportsTemperature: true,
  },
  'gpt-4o-mini-2024-07-18': {
    key: 'gpt-4o-mini-2024-07-18',
    name: 'GPT-4o Mini',
    color: 'bg-orange-500',
    premium: false,
    cost: { input: '$0.15', output: '$0.60' },
    provider: 'OpenAI',
    responseTime: { speed: 'moderate', estimate: '30-60 sec' },
    apiModelName: 'gpt-4o-mini-2024-07-18',
    modelType: 'gpt5_chat',
    contextWindow: 128000,
    releaseDate: '2024-07',
    supportsTemperature: true,
  },
  'o3-mini-2025-01-31': {
    key: 'o3-mini-2025-01-31',
    name: 'o3-mini',
    color: 'bg-red-500',
    premium: true,
    cost: { input: '$1.10', output: '$4.40' },
    provider: 'OpenAI',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'o3-mini-2025-01-31',
    modelType: 'o3_o4',
    contextWindow: 200000,
    releaseDate: '2025-01',
    supportsTemperature: false,
    isReasoning: true,
  },
  'o4-mini-2025-04-16': {
    key: 'o4-mini-2025-04-16',
    name: 'o4-mini',
    color: 'bg-pink-500',
    premium: true,
    cost: { input: '$1.10', output: '$4.40' },
    provider: 'OpenAI',
    responseTime: { speed: 'moderate', estimate: '1-3 min' },
    apiModelName: 'o4-mini-2025-04-16',
    modelType: 'o3_o4',
    contextWindow: 200000,
    releaseDate: '2025-04',
    supportsTemperature: false,
    isReasoning: true,
  },
  'o3-2025-04-16': {
    key: 'o3-2025-04-16',
    name: 'o3-2025-04-16',
    color: 'bg-green-500',
    premium: true,
    cost: { input: '$2', output: '$8' },
    provider: 'OpenAI',
    responseTime: { speed: 'slow', estimate: '3-5+ min' },
    apiModelName: 'o3-2025-04-16',
    modelType: 'o3_o4',
    contextWindow: 400000,
    releaseDate: '2025-04',
    supportsTemperature: false,
    isReasoning: true,
  },
  'gpt-4.1-2025-04-14': {
    key: 'gpt-4.1-2025-04-14',
    name: 'GPT-4.1',
    color: 'bg-yellow-500',
    premium: true,
    cost: { input: '$2.00', output: '$8.00' },
    provider: 'OpenAI',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'gpt-4.1-2025-04-14',
    modelType: 'gpt5_chat',
    contextWindow: 1000000,
    releaseDate: '2025-04',
    supportsTemperature: true,
  },
  'gpt-5-2025-08-07': {
    key: 'gpt-5-2025-08-07',
    name: 'GPT-5',
    color: 'bg-emerald-500',
    premium: true,
    cost: { input: '$1.25', output: '$10.00' },
    provider: 'OpenAI',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'gpt-5-2025-08-07',
    modelType: 'gpt5',
    contextWindow: 400000,
    releaseDate: '2025-08',
    supportsTemperature: false,
    isReasoning: true,
  },
  'gpt-5-chat-latest': {
    key: 'gpt-5-chat-latest',
    name: 'GPT-5 Chat',
    color: 'bg-amber-500',
    premium: false,
    cost: { input: '$1.25', output: '$10.00' },
    provider: 'OpenAI',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'gpt-5-chat-latest',
    modelType: 'gpt5_chat',
    contextWindow: 256000,
    releaseDate: '2025-08',
    supportsTemperature: false,
    isReasoning: false,
  },
  'gpt-5-mini-2025-08-07': {
    key: 'gpt-5-mini-2025-08-07',
    name: 'GPT-5 Mini',
    color: 'bg-indigo-500',
    premium: true,
    cost: { input: '$0.25', output: '$2.00' },
    provider: 'OpenAI',
    responseTime: { speed: 'moderate', estimate: '30-60 sec' },
    apiModelName: 'gpt-5-mini-2025-08-07',
    modelType: 'gpt5',
    contextWindow: 400000,
    releaseDate: '2025-08',
    supportsTemperature: false,
    isReasoning: true,
  },
  'gpt-5-nano-2025-08-07': {
    key: 'gpt-5-nano-2025-08-07',
    name: 'GPT-5 Nano',
    color: 'bg-teal-500',
    premium: false,
    cost: { input: '$0.05', output: '$0.40' },
    provider: 'OpenAI',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'gpt-5-nano-2025-08-07',
    modelType: 'gpt5',
    contextWindow: 400000,
    releaseDate: '2025-08',
    supportsTemperature: false,
    isReasoning: true,
  },

  // Anthropic Models - Direct API
  'claude-sonnet-4-5': {
    key: 'claude-sonnet-4-5-20250929',
    name: 'Claude Sonnet 4.5 (Sep 29 2025)',
    color: 'bg-indigo-500',
    premium: true,
    cost: { input: '$3.00', output: '$15.00' },
    provider: 'Anthropic',
    responseTime: { speed: 'moderate', estimate: '1-3 min' },
    apiModelName: 'claude-sonnet-4-5-20250929',
    modelType: 'claude',
    maxOutputTokens: 64000,
    releaseDate: '2025-09',
    supportsTemperature: true,
    isReasoning: true,
  },

  'claude-sonnet-4-20250514': {
    key: 'claude-sonnet-4-20250514',
    name: 'Claude Sonnet 4',
    color: 'bg-indigo-500',
    premium: true,
    cost: { input: '$3.00', output: '$15.00' },
    provider: 'Anthropic',
    responseTime: { speed: 'moderate', estimate: '1-3 min' },
    apiModelName: 'claude-sonnet-4-20250514',
    modelType: 'claude',
    maxOutputTokens: 64000,
    releaseDate: '2025-05',
    supportsTemperature: true,
    isReasoning: true,
  },
  'claude-3-7-sonnet-20250219': {
    key: 'claude-3-7-sonnet-20250219',
    name: 'Claude 3.7 Sonnet',
    color: 'bg-indigo-400',
    premium: false,
    cost: { input: '$3.00', output: '$15.00' },
    provider: 'Anthropic',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'claude-3-7-sonnet-20250219',
    modelType: 'claude',
    maxOutputTokens: 20000,
    releaseDate: '2025-02',
    supportsTemperature: true,
    isReasoning: true,
  },
  'claude-3-5-sonnet-20241022': {
    key: 'claude-3-5-sonnet-20241022',
    name: 'Claude 3.5 Sonnet',
    color: 'bg-violet-500',
    premium: false,
    cost: { input: '$3.00', output: '$15.00' },
    provider: 'Anthropic',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'claude-3-5-sonnet-20241022',
    modelType: 'claude',
    maxOutputTokens: 8192,
    releaseDate: '2024-10',
    supportsTemperature: true,
    isReasoning: true,
  },
  'claude-3-5-haiku-20241022': {
    key: 'claude-3-5-haiku-20241022',
    name: 'Claude 3.5 Haiku',
    color: 'bg-violet-400',
    premium: false,
    cost: { input: '$0.80', output: '$4.00' },
    provider: 'Anthropic',
    responseTime: { speed: 'moderate', estimate: '30-60 sec' },
    apiModelName: 'claude-3-5-haiku-20241022',
    modelType: 'claude',
    maxOutputTokens: 4000,
    releaseDate: '2024-10',
    supportsTemperature: true,
    isReasoning: true,
  },
  'claude-3-haiku-20240307': {
    key: 'claude-3-haiku-20240307',
    name: 'Claude 3 Haiku',
    color: 'bg-purple-400',
    premium: false,
    cost: { input: '$0.25', output: '$1.25' },
    provider: 'Anthropic',
    responseTime: { speed: 'fast', estimate: '<60 sec' },
    apiModelName: 'claude-3-haiku-20240307',
    modelType: 'claude',
    maxOutputTokens: 4000,
    releaseDate: '2024-03',
    supportsTemperature: true,
    isReasoning: true,
  },

  // Google Gemini Models - Direct API
  'gemini-2.5-pro': {
    key: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    color: 'bg-teal-600',
    premium: true,
    cost: { input: '$2.50', output: '$8.00' },
    provider: 'Gemini',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'models/gemini-2.5-pro',
    modelType: 'gemini',
    contextWindow: 1000000,
    releaseDate: '2025-08',
    supportsTemperature: true,
    isReasoning: true,
  },
  'gemini-2.5-flash': {
    key: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    color: 'bg-teal-500',
    premium: false,
    cost: { input: '$0.70', output: '$2.10' },
    provider: 'Gemini',
    responseTime: { speed: 'moderate', estimate: '30-60 sec' },
    apiModelName: 'models/gemini-2.5-flash',
    modelType: 'gemini',
    contextWindow: 1000000,
    releaseDate: '2025-08',
    supportsTemperature: true,
    isReasoning: true,
  },
  'gemini-2.5-flash-lite': {
    key: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    color: 'bg-teal-400',
    premium: false,
    cost: { input: '$0.35', output: '$1.05' },
    provider: 'Gemini',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'models/gemini-2.5-flash-lite',
    modelType: 'gemini',
    contextWindow: 1000000,
    releaseDate: '2025-08',
    supportsTemperature: true,
    isReasoning: true,
  },
  'gemini-2.0-flash': {
    key: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    color: 'bg-teal-300',
    premium: false,
    cost: { input: '$0.20', output: '$0.60' },
    provider: 'Gemini',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'models/gemini-2.0-flash',
    modelType: 'gemini',
    contextWindow: 1000000,
    releaseDate: '2025-08',
    supportsTemperature: true,
    isReasoning: true,
  },
  'gemini-2.0-flash-lite': {
    key: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash-Lite',
    color: 'bg-teal-200',
    premium: false,
    cost: { input: '$0.10', output: '$0.30' },
    provider: 'Gemini',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'models/gemini-2.0-flash-lite',
    modelType: 'gemini',
    contextWindow: 1000000,
    releaseDate: '2025-08',
    supportsTemperature: true,
    isReasoning: true,
  },

  // DeepSeek Models - Direct API
  'deepseek-chat': {
    key: 'deepseek-chat',
    name: 'DeepSeek Chat',
    color: 'bg-cyan-600',
    premium: false,
    cost: { input: '$0.14', output: '$0.28' },
    provider: 'DeepSeek',
    responseTime: { speed: 'moderate', estimate: '30-90 sec' },
    apiModelName: 'deepseek-chat',
    modelType: 'deepseek',
    supportsTemperature: true,
    isReasoning: false,
  },
  'deepseek-reasoner': {
    key: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner',
    color: 'bg-cyan-800',
    premium: true,
    cost: { input: '$0.55', output: '$2.19' },
    provider: 'DeepSeek',
    responseTime: { speed: 'slow', estimate: '5-10 min' },
    apiModelName: 'deepseek-reasoner',
    modelType: 'deepseek',
    supportsTemperature: false,
    isReasoning: true,
  },

  // OpenRouter-Exclusive Models (Real OpenRouter API models)
  'deepseek/deepseek-v3.1-terminus': {
    key: 'deepseek/deepseek-v3.1-terminus',
    name: 'DeepSeek V3.1 Terminus',
    color: 'bg-cyan-500',
    premium: false,
    cost: { input: '$0.27', output: '$1.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'deepseek/deepseek-v3.1-terminus',
    modelType: 'openrouter',
    contextWindow: 163840,
    maxOutputTokens: 32000,
    releaseDate: '2025-09',
    supportsTemperature: true,
    isReasoning: true,
    supportsStructuredOutput: true,
  },
  'qwen/qwen-plus-2025-07-28:thinking': {
    key: 'qwen/qwen-plus-2025-07-28:thinking',
    name: 'Qwen Plus 0728 (thinking)',
    color: 'bg-orange-700',
    premium: true,
    cost: { input: '$0.40 - $1.20', output: '$4.00 - $12.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'slow', estimate: '2-4 min' },
    apiModelName: 'qwen/qwen-plus-2025-07-28:thinking',
    modelType: 'openrouter',
    contextWindow: 1000000,
    maxOutputTokens: 32800,
    releaseDate: '2025-07',
    supportsTemperature: true,
    isReasoning: true,
    supportsStructuredOutput: false,
  },
  'meta-llama/llama-3.3-70b-instruct': {
    key: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B Instruct',
    color: 'bg-orange-600',
    premium: false,
    cost: { input: '$0.59', output: '$0.79' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'meta-llama/llama-3.3-70b-instruct',
    modelType: 'openrouter',
    contextWindow: 128000,
    maxOutputTokens: 32000,
    releaseDate: '2024-06',
    supportsTemperature: true,
    isReasoning: false,
  },
  'nousresearch/hermes-4-70b': {
    key: 'nousresearch/hermes-4-70b',
    name: 'NousResearch Hermes 4 70B',
    color: 'bg-blue-600',
    premium: false,
    cost: { input: '$0.07', output: '$0.35' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '30-60 sec' },
    apiModelName: 'nousresearch/hermes-4-70b',
    modelType: 'openrouter',
    contextWindow: 32768,
    maxOutputTokens: 25000,
    supportsTemperature: true,
    isReasoning: true,
  },
  'mistralai/mistral-large': {
    key: 'mistralai/mistral-large',
    name: 'Mistral Large',
    color: 'bg-purple-600',
    premium: true,
    cost: { input: '$2.00', output: '$6.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'mistralai/mistral-large',
    modelType: 'openrouter',
    contextWindow: 128000,
    supportsTemperature: true,
    isReasoning: true,
  },
  'deepseek/deepseek-chat-v3.1': {
    key: 'deepseek/deepseek-chat-v3.1',
    name: 'DeepSeek Chat v3.1',
    color: 'bg-cyan-700',
    premium: false,
    cost: { input: '$0.27', output: '$1.10' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '30-90 sec' },
    apiModelName: 'deepseek/deepseek-chat-v3.1',
    modelType: 'openrouter',
    contextWindow: 256000,
    supportsTemperature: true,
    isReasoning: true,
  },
  'openai/gpt-oss-120b': {
    key: 'openai/gpt-oss-120b',
    name: 'OpenAI GPT-OSS 120B',
    color: 'bg-blue-400',
    premium: false,
    cost: { input: '$0.072', output: '$0.28' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '30-60 sec' },
    apiModelName: 'openai/gpt-oss-120b',
    modelType: 'openrouter',
    contextWindow: 131000,
    maxOutputTokens: 20000,
    supportsTemperature: false,
    isReasoning: true,
  },
  'mistralai/codestral-2508': {
    key: 'mistralai/codestral-2508',
    name: 'Mistral Codestral 2508',
    color: 'bg-orange-400',
    premium: false,
    cost: { input: '$0.30', output: '$0.90' },
    provider: 'OpenRouter',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'mistralai/codestral-2508',
    modelType: 'openrouter',
    contextWindow: 256000,
    maxOutputTokens: 8000,
    supportsTemperature: true,
    isReasoning: false,
  },
  'qwen/qwen3-30b-a3b-instruct': {
    key: 'qwen/qwen3-30b-a3b-instruct',
    name: 'Qwen3 30B A3B Instruct',
    color: 'bg-red-400',
    premium: false,
    cost: { input: '$0.10', output: '$0.30' },
    provider: 'OpenRouter',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'qwen/qwen3-30b-a3b-instruct',
    modelType: 'openrouter',
    contextWindow: 262144,
    maxOutputTokens: 30000,
    supportsTemperature: true,
    isReasoning: false,
  },
  'qwen/qwen3-235b-a22b-thinking': {
    key: 'qwen/qwen3-235b-a22b-thinking',
    name: 'Qwen3 235B A22B Thinking',
    color: 'bg-red-700',
    premium: false,
    cost: { input: '$0.70', output: '$8.40' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'qwen/qwen3-235b-a22b-thinking',
    modelType: 'openrouter',
    contextWindow: 131100,
    maxOutputTokens: 32800,
    releaseDate: '2025-07',
    supportsTemperature: true,
    isReasoning: true,
  },
  'qwen/qwen3-coder': {
    key: 'qwen/qwen3-coder',
    name: 'Qwen3 Coder',
    color: 'bg-red-500',
    premium: false,
    cost: { input: '$0.20', output: '$0.80' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '30-60 sec' },
    apiModelName: 'qwen/qwen3-coder',
    modelType: 'openrouter',
    contextWindow: 262144,
    maxOutputTokens: 31000,
    supportsTemperature: true,
    isReasoning: false,
  },
  'moonshotai/kimi-k2': {
    key: 'moonshotai/kimi-k2',
    name: 'Moonshot Kimi K2',
    color: 'bg-slate-600',
    premium: true,
    cost: { input: '$0.14', output: '$2.49' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'moonshotai/kimi-k2',
    modelType: 'openrouter',
    contextWindow: 63000,
    maxOutputTokens: 31000,
    releaseDate: '2025-08',
    supportsTemperature: true,
    isReasoning: true,
  },
  'moonshotai/kimi-k2-0905': {
    key: 'moonshotai/kimi-k2-0905',
    name: 'Moonshot Kimi K2 (Sep 2025)',
    color: 'bg-slate-600',
    premium: true,
    cost: { input: '$1.00', output: '$3.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'moonshotai/kimi-k2-0905',
    modelType: 'openrouter',
    contextWindow: 63000,
    maxOutputTokens: 31000,
    releaseDate: '2025-09',
    supportsTemperature: false,
    isReasoning: true,
  },
  'moonshotai/kimi-dev-72b:free': {
    key: 'moonshotai/kimi-dev-72b:free',
    name: 'Kimi Dev 72B (Free)',
    color: 'bg-slate-400',
    premium: false,
    cost: { input: '$0.00', output: '$0.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'moonshotai/kimi-dev-72b:free',
    modelType: 'openrouter',
    contextWindow: 131072,
    maxOutputTokens: 31000,
    supportsTemperature: true,
    isReasoning: false,
  },
  'x-ai/grok-4': {
    key: 'x-ai/grok-4',
    name: 'Grok 4',
    color: 'bg-gray-900',
    premium: true,
    cost: { input: '$3.00', output: '$15.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'slow', estimate: '3-5+ min' },
    apiModelName: 'x-ai/grok-4',
    modelType: 'openrouter',
    contextWindow: 256000,
    maxOutputTokens: 31000,
    releaseDate: '2025-07',
    supportsTemperature: true,
    isReasoning: true,
  },
  'x-ai/grok-4-fast': {
    key: 'x-ai/grok-4-fast',
    name: 'Grok 4 Fast',
    color: 'bg-orange-500',
    premium: false,
    cost: { input: '$0.20', output: '$0.50' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'x-ai/grok-4-fast:free',
    modelType: 'openrouter',
    contextWindow: 128000,
    maxOutputTokens: 25000,
    releaseDate: '2025-07',
    supportsTemperature: true,
    isReasoning: true,
  },
  'x-ai/grok-3': {
    key: 'x-ai/grok-3',
    name: 'Grok 3',
    color: 'bg-gray-600',
    premium: true,
    cost: { input: '$3.00', output: '$15.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'slow', estimate: '3-5+ min' },
    apiModelName: 'x-ai/grok-3',
    modelType: 'openrouter',
    contextWindow: 256000,
    maxOutputTokens: 31000,
    releaseDate: '2024-11',
    supportsTemperature: true,
    isReasoning: true,
  },
  'x-ai/grok-3-mini': {
    key: 'x-ai/grok-3-mini',
    name: 'Grok 3 Mini',
    color: 'bg-gray-500',
    premium: false,
    cost: { input: '$0.30', output: '$0.50' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'x-ai/grok-3-mini',
    modelType: 'openrouter',
    contextWindow: 256000,
    maxOutputTokens: 31000,
    releaseDate: '2024-11',
    supportsTemperature: true,
    isReasoning: true,
  },
  'x-ai/grok-code-fast-1': {
    key: 'x-ai/grok-code-fast-1',
    name: 'Grok Code Fast 1',
    color: 'bg-gray-400',
    premium: false,
    cost: { input: '$0.20', output: '$1.50' },
    provider: 'OpenRouter',
    responseTime: { speed: 'fast', estimate: '<30 sec' },
    apiModelName: 'x-ai/grok-code-fast-1',
    modelType: 'openrouter',
    contextWindow: 256000,
    maxOutputTokens: 25000,
    releaseDate: '2025-05',
    supportsTemperature: true,
    isReasoning: false,
    requiresPromptFormat: true,
    supportsStructuredOutput: false,
  },
  'nvidia/nemotron-nano-9b-v2': {
    key: 'nvidia/nemotron-nano-9b-v2',
    name: 'Nemotron Nano 9B V2',
    color: 'bg-yellow-600',
    premium: false,
    cost: { input: '$0.00', output: '$0.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'nvidia/nemotron-nano-9b-v2',
    modelType: 'openrouter',
    contextWindow: 128000,
    maxOutputTokens: 24000,
    releaseDate: '2025-09',
    supportsTemperature: false,
    isReasoning: false,
  },
  'qwen/qwen3-max': {
    key: 'qwen/qwen3-max',
    name: 'Qwen3 Max',
    color: 'bg-red-700',
    premium: false,
    cost: { input: '$1.20', output: '$6.00' },
    provider: 'OpenRouter',
    responseTime: { speed: 'slow', estimate: '3-5+ min' },
    apiModelName: 'qwen/qwen3-max',
    modelType: 'openrouter',
    contextWindow: 256000,
    maxOutputTokens: 31000,
    releaseDate: '2025-09',
    supportsTemperature: false,
    isReasoning: false,
  },
  'bytedance/seed-oss-36b-instruct': {
    key: 'bytedance/seed-oss-36b-instruct',
    name: 'Seed OSS 36B Instruct',
    color: 'bg-green-500',
    premium: false,
    cost: { input: '$0.104', output: '$0.415' },
    provider: 'OpenRouter',
    responseTime: { speed: 'moderate', estimate: '1-2 min' },
    apiModelName: 'bytedance/seed-oss-36b-instruct',
    modelType: 'openrouter',
    contextWindow: 131000,
    maxOutputTokens: 30000,
    releaseDate: '2025-09',
    supportsTemperature: false,
    isReasoning: false,
  },
  'stepfun-ai/step3': {
    key: 'stepfun-ai/step3',
    name: 'Step3',
    color: 'bg-green-600',
    premium: true,
    cost: { input: '$0.57', output: '$1.42' },
    provider: 'OpenRouter',
    responseTime: { speed: 'fast', estimate: '10-30 sec' },
    apiModelName: 'stepfun-ai/step3',
    modelType: 'openrouter',
    contextWindow: 65000,
    maxOutputTokens: 25000,
    releaseDate: '2025-08',
    supportsTemperature: false,
    isReasoning: true,
    requiresPromptFormat: true,
  },
};

// Backward compatibility function
export function getDisplayForModelId(modelId: string): ModelDisplay | undefined {
  return MODEL_CATALOG[modelId];
}